# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0433a922e34a0a36ad945702ffec8ec462a79a48f71c5434b72e3e8e2b3a10495018edeab2c29a71a1edabfe3d14f3dd259e63ac38add91cba4ccc63129930d4

test:
  secret_key_base: 52fd61558e0394949d0d983f424e664836b296fb67ef0127ee038ef09a4ecf515867956d130066f91293bba734519294c52bbcb8c2c1f3763ca3f9c4012c6db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
